//AUTOGENERATED FILE FROM png2asset
// Conversion args: /brickwall.png -tiles_only -keep_palette_order -o /brickwall.c

#ifndef METASPRITE_brickwall_H
#define METASPRITE_brickwall_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define brickwall_TILE_ORIGIN 0
#define brickwall_TILE_W 8
#define brickwall_TILE_H 16
#define brickwall_WIDTH 8
#define brickwall_HEIGHT 8
#define brickwall_TILE_COUNT 2
#define brickwall_PALETTE_COUNT 1
#define brickwall_COLORS_PER_PALETTE 4
#define brickwall_TOTAL_COLORS 4

BANKREF_EXTERN(brickwall)

extern const palette_color_t brickwall_palettes[4];
extern const uint8_t brickwall_tiles[32];

#endif
