//AUTOGENERATED FILE FROM png2asset
// Conversion args: /crate.png -tiles_only -keep_palette_order -o /crate.c

#ifndef METASPRITE_crate_H
#define METASPRITE_crate_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define crate_TILE_ORIGIN 0
#define crate_TILE_W 8
#define crate_TILE_H 16
#define crate_WIDTH 16
#define crate_HEIGHT 16
#define crate_TILE_COUNT 4
#define crate_PALETTE_COUNT 1
#define crate_COLORS_PER_PALETTE 4
#define crate_TOTAL_COLORS 4

BANKREF_EXTERN(crate)

extern const palette_color_t crate_palettes[4];
extern const uint8_t crate_tiles[64];

#endif
