//AUTOGENERATED FILE FROM png2asset
// Conversion args: /dingbats.png -tiles_only -spr8x8 -keep_palette_order -keep_duplicate_tiles -noflip -o /dingbats.c

#ifndef METASPRITE_dingbats_H
#define METASPRITE_dingbats_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dingbats_TILE_ORIGIN 0
#define dingbats_TILE_W 8
#define dingbats_TILE_H 8
#define dingbats_WIDTH 96
#define dingbats_HEIGHT 8
#define dingbats_TILE_COUNT 12
#define dingbats_PALETTE_COUNT 1
#define dingbats_COLORS_PER_PALETTE 4
#define dingbats_TOTAL_COLORS 4

BANKREF_EXTERN(dingbats)

extern const palette_color_t dingbats_palettes[4];
extern const uint8_t dingbats_tiles[192];

#endif
