//AUTOGENERATED FILE FROM png2asset
// Conversion args: /exit-sign.png -map -sw 24 -sh 8 -keep_palette_order -keep_duplicate_tiles -noflip -o /exit_sign.c

#ifndef METASPRITE_exit_sign_H
#define METASPRITE_exit_sign_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define exit_sign_TILE_ORIGIN 0
#define exit_sign_TILE_W 8
#define exit_sign_TILE_H 8
#define exit_sign_WIDTH 24
#define exit_sign_HEIGHT 8
#define exit_sign_TILE_COUNT 3
#define exit_sign_PALETTE_COUNT 1
#define exit_sign_COLORS_PER_PALETTE 4
#define exit_sign_TOTAL_COLORS 4
#define exit_sign_MAP_ATTRIBUTES 0
extern const unsigned char exit_sign_map[3];
#define exit_sign_map_attributes exit_sign_map

BANKREF_EXTERN(exit_sign)

extern const palette_color_t exit_sign_palettes[4];
extern const uint8_t exit_sign_tiles[48];

#endif
