//AUTOGENERATED FILE FROM png2asset
// Conversion args: /floor.png -tiles_only -keep_palette_order -o /floor.c

#ifndef METASPRITE_floor_H
#define METASPRITE_floor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define floor_TILE_ORIGIN 0
#define floor_TILE_W 8
#define floor_TILE_H 16
#define floor_WIDTH 8
#define floor_HEIGHT 8
#define floor_TILE_COUNT 2
#define floor_PALETTE_COUNT 1
#define floor_COLORS_PER_PALETTE 4
#define floor_TOTAL_COLORS 4

BANKREF_EXTERN(floor)

extern const palette_color_t floor_palettes[4];
extern const uint8_t floor_tiles[32];

#endif
