//AUTOGENERATED FILE FROM png2asset
// Conversion args: /robot.png -spr8x16 -sw 16 -sh 16 -keep_palette_order -o /robot.c

#ifndef METASPRITE_robot_H
#define METASPRITE_robot_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define robot_TILE_ORIGIN 0
#define robot_TILE_W 8
#define robot_TILE_H 16
#define robot_WIDTH 16
#define robot_HEIGHT 16
#define robot_TILE_COUNT 10
#define robot_PALETTE_COUNT 1
#define robot_COLORS_PER_PALETTE 4
#define robot_TOTAL_COLORS 4
#define robot_PIVOT_X 8
#define robot_PIVOT_Y 8
#define robot_PIVOT_W 16
#define robot_PIVOT_H 16
extern const metasprite_t* const robot_metasprites[4];

BANKREF_EXTERN(robot)

extern const palette_color_t robot_palettes[4];
extern const uint8_t robot_tiles[160];

#endif
